version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  traefik:
    image: traefik:v2.0
    container_name: prom_traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entrypoint=metrics"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prom_prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`prom.lan`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: prom_node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    container_name: prom_alertmanager
    ports:
      - 9093:9093
    volumes:
      - "./alertmanager/:/etc/alertmanager/"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: prom_grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    user: "104"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.lan`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    restart: unless-stopped

  blackbox:
    expose:
      - 9115
    ports:
      - 9115:9115
    image: prom/blackbox-exporter
    container_name: prom_blackblox
    volumes:
      - ./blackbox/config:/config
    command:
      - '--config.file=/config/blackbox.yml'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blackbox.rule=Host(`bb.lan`)"
      - "traefik.http.services.blackbox.loadbalancer.server.port=9115"
    restart: unless-stopped
